language: node_js
node_js:
  - "10"
  - "12"
  - "node" # latest
cache: yarn
addons:
  firefox: latest
script:
  - yarn install
  - yarn lint
  - yarn test
email:
  on_failure: change
  on_success: never

